CREATE TABLE Categoria (
    codigoCategoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    caracteristicasAlmacenamiento VARCHAR2(200) NOT NULL,             
    nombreCategoria VARCHAR2(200) NOT NULL,                          
    descripcion VARCHAR2(200) NOT NULL,                              
    PRODUCTO_codigoBarras VARCHAR2(100),                                      
    CONSTRAINT chk_codigoCategoria CHECK (codigoCategoria > 0),     
    CONSTRAINT fk_codigoBarrasP FOREIGN KEY (PRODUCTO_codigoBarras)           
        REFERENCES Producto(codigoBarras)                            
);
