CREATE TABLE OrdenCompra (
    idOrden INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    fechaCreacion DATE NOT NULL CHECK (fechaCreacion <= SYSDATE),  
    estado VARCHAR2(50) NOT NULL,                                
    fechaEntrega DATE NOT NULL CHECK (fechaEntrega > fechaCreacion), 
    PROVEEDOR_NIT INT,                                                    
    PRODUCTO_codigoBarras VARCHAR2(100),                               
    SUCURSAL_idSucursal INT,                                   
    CONSTRAINT fk_proveedorOC FOREIGN KEY (PROVEEDOR_NIT)                 
        REFERENCES Proveedor(NIT),                             
    CONSTRAINT fk_productoOC FOREIGN KEY (PRODUCTO_codigoBarras)        
        REFERENCES Producto(codigoBarras),                    
    CONSTRAINT fk_sucursalOC FOREIGN KEY (SUCURSAL_idSucursal)  
        REFERENCES Sucursal(idSucursal)                        
);
